export const MEDIA_URLS = {
    CV_PDF_URL: '/documents/younes-alturkey-cv.pdf',
    IELTS_PDF_URL: '/documents/younes-alturkey-ielts.pdf',
    CSD_PDF_URL: '/documents/younes-alturkey-csd.pdf',
    SAFE_PRACTITIONER_PDF_URL:
        '/documents/younes-alturkey-safe-practitioner.pdf',
    SAFE_SM_PDF_URL: '/documents/younes-alturkey-safe-sm.pdf',
    SA_CSD_PDF_URL: '/documents/younes-alturkey-sa-csd.pdf',
    BSC_PDF_URL: '/documents/younes-alturkey-bachelor.pdf',
    SCE_PDF_URL: '/documents/younes-alturkey-sce.pdf',
    ASIF_LETTER_PDF_URL: '/documents/younes-alturkey-dr-asif-letter.pdf',
    VIJEY_LETTER_PDF_URL: '/documents/younes-alturkey-dr-vijey-letter.pdf',
    BEST_CODE_PDF_URL: '/documents/younes-alturkey-best-code.pdf',
    TUWAIQ_PDF_URL: '/documents/younes-alturkey-tuwaiq.pdf',
    YOUNES_IMG_URL: '/images/younes-official.jpg',
    ALBAIK_IMG_URL: '/images/albaik_logo.png',
    BHR_IMG_URL: '/images/bhr.png',
    NOT_FOUND_IMG_URL: '/images/404.svg',
    IELTS_IMG_URL: '/images/ielts.png',
    CSM_IMG_URL: '/images/csm.png',
    NUQTAH_URL: '/images/nuqtah.webp',
    NAHDI_URL: '/images/nahdi.svg',
    MCIT_URL: '/images/mcit.png',
    ACSM_IMG_URL: '/images/acsm.png',
    CSPSM_IMG_URL: '/images/cspsm.png',
    NELC_IMG_URL: '/images/nelc.svg',
    YAT_IMG_URL: '/images/logo.png',
    KAU_IMG_URL: '/images/kau.png',
    SAFCSP_IMG_URL: '/images/safcsp.png',
    SCE_IMG_URL: '/images/sce.png',
    TS_IMG_URL: '/images/ts.png',
    JS_IMG_URL: '/images/js.png',
    CSHARP_IMG_URL: '/images/csharp.png',
    HTML_IMG_URL: '/images/html.png',
    CSS_IMG_URL: '/images/css.png',
    ADOBEXD_IMG_URL: '/images/adobexd.png',
    APACHE_IMG_URL: '/images/apache.png',
    CPANEL_IMG_URL: '/images/cpanel.png',
    DOTNET_IMG_URL: '/images/dotnet.png',
    FIGMA_IMG_URL: '/images/figma.png',
    NEXT_IMG_URL: '/images/next.png',
    NGINX_IMG_URL: '/images/nginx.png',
    NODE_IMG_URL: '/images/node.png',
    REACT_IMG_URL: '/images/react.png',
    TAILWINDCSS_IMG_URL: '/images/tailwindcss.png',
    WORDPRESS_IMG_URL: '/images/wordpress.png',
    REDUX_IMG_URL: '/images/redux.png',
    AZURE_IMG_URL: '/images/azure.png',
    AZUREDEVOPS_IMG_URL: '/images/azuredevops.png',
    GIT_IMG_URL: '/images/git.png',
    ELECTRON_IMG_URL: '/images/electron.png',
    MONGODB_IMG_URL: '/images/mongodb.png',
    MYSQL_IMG_URL: '/images/mysql.png',
    SQLITE_IMG_URL: '/images/sqlite.png',
    POSTGRES_IMG_URL: '/images/postgress.png',
    SOLIDITY_IMG_URL: '/images/solidity.png',
    POSTMAN_IMG_URL: '/images/postman.png',
    WEBSOCKETS_IMG_URL: '/images/websockets.png',
    CSD_IMG_URL: '/images/csd.png',
    SA_CSD_IMG_URL: '/images/sa-csm.png',
    SAFE_PRACTITIONER_IMG_URL: '/images/safe-practitioner.png',
    SAFE_SM_IMG_URL: '/images/safe-sm.png',
}

export const EXTERNAL_URLS = {
    YAT_EMAIL_URL: 'mailto:hi@younes.ai',
    YAT_PHONENUMBER_URL: 'tel:+966538654514',
    YAT_LINKEDIN_URL: 'https://www.linkedin.com/in/younes-alturkey',
    YAT_GITHUB_URL: 'https://github.com/younes-alturkey',
    YAT_MEDIUM_URL: 'https://medium.com/@younes-alturkey',
    YAT_CODEPEN_URL: 'https://codepen.io/younes-alturkey',
    YAT_BEHANCE_URL: 'https://www.behance.net/younesalturkey',
    YAT_TWITTER_URL: 'https://twitter.com/younes_alturkey',
    YAT_REDDIT_URL: 'https://www.reddit.com/user/younes_alturkey',
    BITCHUNK_GITHUB_URL: 'https://github.com/younes-alturkey/bitchunk',
    BITCHUNK_URL: 'https://bit-chunk.netlify.app',
    SPACESHOOTER_GITHUB_URL: 'https://github.com/younes-alturkey/spaceshooter',
    SPACESHOOTER_URL: 'https://2d-spaceshooter.netlify.app',
    NAHDIIN_GITHUB_URL: 'https://github.com/younes-alturkey/nahdi-in',
    NAHDIIN_URL: 'https://nahdiin.netlify.app',
    NAHDIMOBILE_GITHUB_URL: 'https://github.com/younes-alturkey/nahdi-mobile',
    NAHDIMOBILE_URL: 'https://github.com/younes-alturkey/nahdi-mobile',
    SOUDAHATS_GITHUB_URL:
        'https://github.com/younes-alturkey/soudah-scholarship-ats',
    SOUDAHATS_URL: 'https://soudah-ats.netlify.app',
    NUQTAH_URL: 'https://itsnuqtah.com',
    SPF_URL: 'https://shaheenspf.sa',
    ADMINDASHBOARD_URL: 'https://ya-admin-dashboard.vercel.app',
    ADMINDASHBOARD_CODE_URL:
        'https://github.com/younes-alturkey/admin-dashboard',
}

export const ARTICLES_URLS = {
    LAWSOFUX10_MEDIUM_URL:
        'https://medium.com/@younes-alturkey/10-laws-for-effective-user-experince-74aae39e2abf',
    LAWSOFUX10_LINKEDIN_URL:
        'https://www.linkedin.com/pulse/10-laws-effective-user-experince-younes-alturkey',
    BECOMINGWORLDCLASS_LINKEDIN_URL:
        'https://www.linkedin.com/pulse/becoming-world-class-simpler-than-entry-level-jobs-younes-alturkey',
}
