import { Metadata } from '@/src/components/Head'

const metadata: Metadata = {
    title: 'Younes Alturkey',
    keywords:
        'software engineer, AI engineer, full-stack, full-stack software engineer, product manager, product development, agile, ci/cd, devops, web development, mobile development, cloud computing, machine learning, artificial intelligence, AI, browser development, reactjs, nextjs, tailwindcss, dotnet, csharp, javascript, typescript, css, scss, html',
    description: `I'm a seasoned full-stack software engineer with extensive experience in web, mobile, desktop, and API development. I have a proven track record of enhancing productivity and delivering high-impact results in large companies. My leadership has guided teams to create robust, user-friendly solutions. My expertise spans computer science and product development, driving innovation and excellence in every project. I'm proficient in JavaScript, TypeScript, C#, Python, CSS, SCSS, TailwindCSS, HTML, ReactJS/NextJS, ElectronJS, .NET, Docker, CI/CD, DevOps, Linux, AWS, GCP, UX/UI, PRD; and agile practices.`,
    subject: 'Younes Alturkey',
    language: 'en',
    robots: 'index, follow',
    revised: '2030-12-31',
    abstract: 'Younes Alturkey',
    topic: 'Professional Software Engineer',
    summary: `I'm a seasoned full-stack software engineer with extensive experience in web, mobile, desktop, and API development. I have a proven track record of enhancing productivity and delivering high-impact results in large companies. My leadership has guided teams to create robust, user-friendly solutions. My expertise spans computer science and product development, driving innovation and excellence in every project. I'm proficient in JavaScript, TypeScript, C#, Python, CSS, SCSS, TailwindCSS, HTML, ReactJS/NextJS, ElectronJS, .NET, Docker, CI/CD, DevOps, Linux, AWS, GCP, UX/UI, PRD; and agile practices.`,
    classification: `I'm a seasoned full-stack software engineer with extensive experience in web, mobile, desktop, and API development. I have a proven track record of enhancing productivity and delivering high-impact results in large companies. My leadership has guided teams to create robust, user-friendly solutions. My expertise spans computer science and product development, driving innovation and excellence in every project. I'm proficient in JavaScript, TypeScript, C#, Python, CSS, SCSS, TailwindCSS, HTML, ReactJS/NextJS, ElectronJS, .NET, Docker, CI/CD, DevOps, Linux, AWS, GCP, UX/UI, PRD; and agile practices.`,
    author: 'Younes Alturkey',
    designer: 'Younes Alturkey',
    replyTo: 'hi@younes.ai',
    owner: 'Younes Alturkey',
    url: 'https://younes.ai',
    identifierURL: 'https://younes.ai',
    directory: 'Software Engineering/Product Development',
    category: 'Software Engineering/Product Development',
    coverage: 'Global',
    distribution: 'Global',
    rating: 'General',
    revisitAfter: '7 days',
    themeColor: '#F12F40',
    icon: 'https://younes.ai/favicon.ico',
    ogTitle: 'Younes Alturkey',
    ogType: 'website',
    ogUrl: 'https://younes.ai',
    ogImage: 'https://younes.ai/images/younes-in-the-media.png',
    ogSiteName: 'Younes Alturkey',
    ogDescription: `I'm a seasoned full-stack software engineer with extensive experience in web, mobile, desktop, and API development. I have a proven track record of enhancing productivity and delivering high-impact results in large companies. My leadership has guided teams to create robust, user-friendly solutions. My expertise spans computer science and product development, driving innovation and excellence in every project. I'm proficient in JavaScript, TypeScript, C#, Python, CSS, SCSS, TailwindCSS, HTML, ReactJS/NextJS, ElectronJS, .NET, Docker, CI/CD, DevOps, Linux, AWS, GCP, UX/UI, PRD; and agile practices.`,
    ogEmail: 'hi@younes.ai',
    ogPhoneNumber: '+966538654514',
    ogFaxNumber: '+966538654514',
    ogLatitude: '34.709360181464948',
    ogLongitude: '76.67509523068262',
    ogStreetAddress: 'Riyadh',
    ogLocality: 'Riyadh',
    ogRegion: 'Riyadh',
    ogPostalCode: '13254',
    ogCountryName: 'Saudi Arabia',
    twitterCard: 'summary_large_image',
    twitterSite: '@younes_alturkey',
    twitterCreator: '@younes_alturkey',
    twitterUrl: 'https://younes.ai',
    twitterTitle: 'Younes Alturkey',
    twitterDescription: `I'm a seasoned full-stack software engineer with extensive experience in web, mobile, desktop, and API development. I have a proven track record of enhancing productivity and delivering high-impact results in large companies. My leadership has guided teams to create robust, user-friendly solutions. My expertise spans computer science and product development, driving innovation and excellence in every project. I'm proficient in JavaScript, TypeScript, C#, Python, CSS, SCSS, TailwindCSS, HTML, ReactJS/NextJS, ElectronJS, .NET, Docker, CI/CD, DevOps, Linux, AWS, GCP, UX/UI, PRD; and agile practices.`,
    twitterImage: 'https://younes.ai/images/younes-in-the-media.png',
    appleMobileWebAppTitle: 'Younes Alturkey',
    applicationName: 'Younes Alturkey',
    msapplicationTileColor: '#F12F40',
    msapplicationTileImage: 'https://younes.ai/favicon.ico',
    canonicalLink: 'https://younes.ai',
}

export default metadata
